version: "2"
linters-settings:
    custom:
      myloglint:
        path: ./lint-plugin/lint-plugin
        description: "Checks for first lower case letter, english letters, emoji's and special characters and sensitive data in logs"


linters:
  enable:
    - myloglint
